name: CI
on: push

env:
  NODE_OPTIONS: --max_old_space_size=8192

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-
      - run: yarn install --immutable
      - run: yarn build:icons
      - run: yarn chromatic --exit-once-uploaded --exit-zero-on-changes
        working-directory: storybook/
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          STORYBOOK_BUILD_TIMEOUT: 1200000 # 20 minutes
      - run: cat /home/runner/work/styled-icons/styled-icons/storybook/build-storybook.log || true
        if: always()

  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
        id: yarn-cache-dir-path
      - uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-
      - run: yarn install --immutable
      - run: yarn fmt:check
      - run: yarn mrl check
